### ISSUE TITLE
unable to install the extension

### ISSUE THREAD

**Issue by Deepali2** [xahon/vscode-paper#1]
I am unable to install the extension on my visual studio code. When I click install it gives me the message "Failed to install 'xahon.vscode-paper'." It prompts me to manually install. I do that but then nothing happens. It does not install. Any ideas?

**Comment by xahon** [comment]
@Deepali2 Hello.
Thanks for reporting the issue.
Sorry for the inconvenience, I've updated it.
Tested on windows 10, vscode 1.27.2 and vscode-insider 1.29.0

**Comment by xahon** [comment]
@Deepali2 Give me know whether it works for you
